import bpy

actions_to_keep = ["Afk 01_Belly-Global",
"Afk 01_Chest-Global",
"Afk 01_Controller-Global",
"Afk 01_Head-Global",
"Afk 01_Hip-Global",
"Afk 01_Left_Arm-Global",
"Afk 01_Left_Foot-Global",
"Afk 01_Left_Forearm-Global",
"Afk 01_Left_Hand-Global",
"Afk 01_Left_Leg-Global",
"Afk 01_Left_Thigh-Global",
"Afk 01_Right_Arm-Global",
"Afk 01_Right_Foot-Global",
"Afk 01_Right_Forearm-Global",
"Afk 01_Right_Hand-Global",
"Afk 01_Right_Leg-Global",
"Afk 01_Right_Thigh-Global",
"Attack 01_Belly-Global",
"Attack 01_Chest-Global",
"Attack 01_Controller-Global",
"Attack 01_Head-Global",
"Attack 01_Hip-Global",
"Attack 01_Left_Arm-Global",
"Attack 01_Left_Foot-Global",
"Attack 01_Left_Forearm-Global",
"Attack 01_Left_Hand-Global",
"Attack 01_Left_Leg-Global",
"Attack 01_Left_Thigh-Global",
"Attack 01_Right_Arm-Global",
"Attack 01_Right_Foot-Global",
"Attack 01_Right_Forearm-Global",
"Attack 01_Right_Hand-Global",
"Attack 01_Right_Leg-Global",
"Attack 01_Right_Thigh-Global",
"Attack 03_Belly-Global",
"Attack 03_Chest-Global",
"Attack 03_Controller-Global",
"Attack 03_Head-Global",
"Attack 03_Hip-Global",
"Attack 03_Left_Arm-Global",
"Attack 03_Left_Foot-Global",
"Attack 03_Left_Forearm-Global",
"Attack 03_Left_Hand-Global",
"Attack 03_Left_Leg-Global",
"Attack 03_Left_Thigh-Global",
"Attack 03_Right_Arm-Global",
"Attack 03_Right_Foot-Global",
"Attack 03_Right_Forearm-Global",
"Attack 03_Right_Hand-Global",
"Attack 03_Right_Leg-Global",
"Attack 03_Right_Thigh-Global",
"Attack 04_Belly-Global",
"Attack 04_Chest-Global",
"Attack 04_Controller-Global",
"Attack 04_Head-Global",
"Attack 04_Hip-Global",
"Attack 04_Left_Arm-Global",
"Attack 04_Left_Foot-Global",
"Attack 04_Left_Forearm-Global",
"Attack 04_Left_Hand-Global",
"Attack 04_Left_Leg-Global",
"Attack 04_Left_Thigh-Global",
"Attack 04_Right_Arm-Global",
"Attack 04_Right_Foot-Global",
"Attack 04_Right_Forearm-Global",
"Attack 04_Right_Hand-Global",
"Attack 04_Right_Leg-Global",
"Attack 04_Right_Thigh-Global",
"Dance Scissors 01_Belly-Global",
"Dance Scissors 01_Chest-Global",
"Dance Scissors 01_Controller-Global",
"Dance Scissors 01_Head-Global",
"Dance Scissors 01_Hip-Global",
"Dance Scissors 01_Left_Arm-Global",
"Dance Scissors 01_Left_Foot-Global",
"Dance Scissors 01_Left_Forearm-Global",
"Dance Scissors 01_Left_Hand-Global",
"Dance Scissors 01_Left_Leg-Global",
"Dance Scissors 01_Left_Thigh-Global",
"Dance Scissors 01_Right_Arm-Global",
"Dance Scissors 01_Right_Foot-Global",
"Dance Scissors 01_Right_Forearm-Global",
"Dance Scissors 01_Right_Hand-Global",
"Dance Scissors 01_Right_Leg-Global",
"Dance Scissors 01_Right_Thigh-Global",
"Death 01_Belly-Global",
"Death 01_Chest-Global",
"Death 01_Controller-Global",
"Death 01_Head-Global",
"Death 01_Hip-Global",
"Death 01_Left_Arm-Global",
"Death 01_Left_Foot-Global",
"Death 01_Left_Forearm-Global",
"Death 01_Left_Hand-Global",
"Death 01_Left_Leg-Global",
"Death 01_Left_Thigh-Global",
"Death 01_Right_Arm-Global",
"Death 01_Right_Foot-Global",
"Death 01_Right_Forearm-Global",
"Death 01_Right_Hand-Global",
"Death 01_Right_Leg-Global",
"Death 01_Right_Thigh-Global",
"Dodge 01_Belly-Global",
"Dodge 01_Chest-Global",
"Dodge 01_Controller-Global",
"Dodge 01_Head-Global",
"Dodge 01_Hip-Global",
"Dodge 01_Left_Arm-Global",
"Dodge 01_Left_Foot-Global",
"Dodge 01_Left_Forearm-Global",
"Dodge 01_Left_Hand-Global",
"Dodge 01_Left_Leg-Global",
"Dodge 01_Left_Thigh-Global",
"Dodge 01_Right_Arm-Global",
"Dodge 01_Right_Foot-Global",
"Dodge 01_Right_Forearm-Global",
"Dodge 01_Right_Hand-Global",
"Dodge 01_Right_Leg-Global",
"Dodge 01_Right_Thigh-Global",
"Fall 01_Belly-Global",
"Fall 01_Chest-Global",
"Fall 01_Controller-Global",
"Fall 01_Head-Global",
"Fall 01_Hip-Global",
"Fall 01_Left_Arm-Global",
"Fall 01_Left_Foot-Global",
"Fall 01_Left_Forearm-Global",
"Fall 01_Left_Hand-Global",
"Fall 01_Left_Leg-Global",
"Fall 01_Left_Thigh-Global",
"Fall 01_Right_Arm-Global",
"Fall 01_Right_Foot-Global",
"Fall 01_Right_Forearm-Global",
"Fall 01_Right_Hand-Global",
"Fall 01_Right_Leg-Global",
"Fall 01_Right_Thigh-Global",
"Get Hit 01_Belly-Global",
"Get Hit 01_Chest-Global",
"Get Hit 01_Controller-Global",
"Get Hit 01_Head-Global",
"Get Hit 01_Hip-Global",
"Get Hit 01_Left_Arm-Global",
"Get Hit 01_Left_Foot-Global",
"Get Hit 01_Left_Forearm-Global",
"Get Hit 01_Left_Hand-Global",
"Get Hit 01_Left_Leg-Global",
"Get Hit 01_Left_Thigh-Global",
"Get Hit 01_Right_Arm-Global",
"Get Hit 01_Right_Foot-Global",
"Get Hit 01_Right_Forearm-Global",
"Get Hit 01_Right_Hand-Global",
"Get Hit 01_Right_Leg-Global",
"Get Hit 01_Right_Thigh-Global",
"Heavy Attack 01_Belly-Global",
"Heavy Attack 01_Chest-Global",
"Heavy Attack 01_Controller-Global",
"Heavy Attack 01_Head-Global",
"Heavy Attack 01_Hip-Global",
"Heavy Attack 01_Left_Arm-Global",
"Heavy Attack 01_Left_Foot-Global",
"Heavy Attack 01_Left_Forearm-Global",
"Heavy Attack 01_Left_Hand-Global",
"Heavy Attack 01_Left_Leg-Global",
"Heavy Attack 01_Left_Thigh-Global",
"Heavy Attack 01_Right_Arm-Global",
"Heavy Attack 01_Right_Foot-Global",
"Heavy Attack 01_Right_Forearm-Global",
"Heavy Attack 01_Right_Hand-Global",
"Heavy Attack 01_Right_Leg-Global",
"Heavy Attack 01_Right_Thigh-Global",
"Heavy Attack Holding 01_Belly-Global",
"Heavy Attack Holding 01_Chest-Global",
"Heavy Attack Holding 01_Controller-Global",
"Heavy Attack Holding 01_Head-Global",
"Heavy Attack Holding 01_Hip-Global",
"Heavy Attack Holding 01_Left_Arm-Global",
"Heavy Attack Holding 01_Left_Foot-Global",
"Heavy Attack Holding 01_Left_Forearm-Global",
"Heavy Attack Holding 01_Left_Hand-Global",
"Heavy Attack Holding 01_Left_Leg-Global",
"Heavy Attack Holding 01_Left_Thigh-Global",
"Heavy Attack Holding 01_Right_Arm-Global",
"Heavy Attack Holding 01_Right_Foot-Global",
"Heavy Attack Holding 01_Right_Forearm-Global",
"Heavy Attack Holding 01_Right_Hand-Global",
"Heavy Attack Holding 01_Right_Leg-Global",
"Heavy Attack Holding 01_Right_Thigh-Global",
"Idle 01_Belly-Global",
"Idle 01_Chest-Global",
"Idle 01_Controller-Global",
"Idle 01_Head-Global",
"Idle 01_Hip-Global",
"Idle 01_Left_Arm-Global",
"Idle 01_Left_Foot-Global",
"Idle 01_Left_Forearm-Global",
"Idle 01_Left_Hand-Global",
"Idle 01_Left_Leg-Global",
"Idle 01_Left_Thigh-Global",
"Idle 01_Right_Arm-Global",
"Idle 01_Right_Foot-Global",
"Idle 01_Right_Forearm-Global",
"Idle 01_Right_Hand-Global",
"Idle 01_Right_Leg-Global",
"Idle 01_Right_Thigh-Global",
"Jump 01_Belly-Global",
"Jump 01_Chest-Global",
"Jump 01_Controller-Global",
"Jump 01_Head-Global",
"Jump 01_Hip-Global",
"Jump 01_Left_Arm-Global",
"Jump 01_Left_Foot-Global",
"Jump 01_Left_Forearm-Global",
"Jump 01_Left_Hand-Global",
"Jump 01_Left_Leg-Global",
"Jump 01_Left_Thigh-Global",
"Jump 01_Right_Arm-Global",
"Jump 01_Right_Foot-Global",
"Jump 01_Right_Forearm-Global",
"Jump 01_Right_Hand-Global",
"Jump 01_Right_Leg-Global",
"Jump 01_Right_Thigh-Global",
"Land 01_Belly-Global",
"Land 01_Chest-Global",
"Land 01_Controller-Global",
"Land 01_Head-Global",
"Land 01_Hip-Global",
"Land 01_Left_Arm-Global",
"Land 01_Left_Foot-Global",
"Land 01_Left_Forearm-Global",
"Land 01_Left_Hand-Global",
"Land 01_Left_Leg-Global",
"Land 01_Left_Thigh-Global",
"Land 01_Right_Arm-Global",
"Land 01_Right_Foot-Global",
"Land 01_Right_Forearm-Global",
"Land 01_Right_Hand-Global",
"Land 01_Right_Leg-Global",
"Land 01_Right_Thigh-Global",
"Run 01_Belly-Global"
"Run 01_Chest-Global",
"Run 01_Controller-Global",
"Run 01_Head-Global",
"Run 01_Hip-Global",
"Run 01_Left_Arm-Global",
"Run 01_Left_Foot-Global",
"Run 01_Left_Forearm-Global",
"Run 01_Left_Hand-Global",
"Run 01_Left_Leg-Global",
"Run 01_Left_Thigh-Global",
"Run 01_Right_Arm-Global",
"Run 01_Right_Foot-Global",
"Run 01_Right_Forearm-Global",
"Run 01_Right_Hand-Global",
"Run 01_Right_Leg-Global",
"Run 01_Right_Thigh-Global"]

# Loop through all actions in the file using a copy of the list
for action in bpy.data.actions[:]:  # The slice [:] creates a copy of the list to iterate over
    if action.name not in actions_to_keep:
        # If the action has no users or is not set to any user's active action, it can be removed
        print("Deleted" + action.name)
        bpy.data.actions.remove(action)

print("Deletion completed")